fix
Drincann/Mirai-js pull request #214
Opened 2022-07-29 13:07 UTC by Mantou1233

#213

2022-07-30 10:49 UTC, Drincann requested changes
core 下有两个修改夹带。

2022-08-01 07:49 UTC, FurryR commented
反对：`Bot.d.ts`仅作类型提示用，更改为实际字面量或类型并不会导致程序逻辑异常。

同意：在`src/core`下检测到了和本pr相同的错误，等一下我会再开一个PR修正错误。

2022-08-01 14:11 UTC, Drincann commented
> 反对：`Bot.d.ts`仅作类型提示用，更改为实际字面量或类型并不会导致程序逻辑异常。
> 
> 同意：在`src/core`下检测到了和本pr相同的错误，等一下我会再开一个PR修正错误。

你说的相同的错误应该是他这里前一段时间 pr 没同步这个仓库导致的夹带，那些地方主要是为了适配 api 的新结构，该改的地方已经改过了。

这个 pr 主要是为了解决 GroupPermission 的问题，在 ts 中 type checker 会认为 groupPermission.ADMIN 有三种值，这实际上是有问题的。

2022-08-01 14:26 UTC, Mantou1233 reviewed
-

2022-08-01 14:29 UTC, FurryR commented
> > 反对：`Bot.d.ts`仅作类型提示用，更改为实际字面量或类型并不会导致程序逻辑异常。
> > 同意：在`src/core`下检测到了和本pr相同的错误，等一下我会再开一个PR修正错误。
> 
> @FurryR ，你说的相同的错误应该是指，前一段时间的 pr closed 后没同步这个仓库导致的修改夹带，这些夹带的地方主要是为了适配 api 的新结构，这部分逻辑该改的地方已经改过了，目前不需要修改。
> 
> 这个 pr 主要是为了解决 GroupPermission 的问题，在 ts 中 type checker 会认为 groupPermission.ADMIN 有三种值，这实际上是有问题的。

@Drincann 应该是这样。但是最新版仍有一个`core`内的内容错误套用2层data（axios加注type lint后报错）。
我已经尝试`npm update`，但问题依旧存在，所以请至少review一遍。

2022-08-01 14:54 UTC, Drincann commented
@FurryR 具体描述一下报错的复现步骤。

2022-08-01 15:03 UTC, Drincann commented
[mah v1 GET /config](https://github.com/project-mirai/mirai-api-http/blob/fdecc7d6ce3128f9f56465715e79dff7e5c7f9ff/docs/API.md#session%E9%85%8D%E7%BD%AE) 这个接口很可能返回了 `{data: any, code: number, msg: string}`。

请问在 mah v1 下测过了吗。

2022-08-01 15:14 UTC, FurryR commented
> [mah v1 GET /config](https://github.com/project-mirai/mirai-api-http/blob/fdecc7d6ce3128f9f56465715e79dff7e5c7f9ff/docs/API.md#session%E9%85%8D%E7%BD%AE) 这个接口很可能返回了 `{data: any, code: number, msg: string}`。
> 
> 请问在 mah v1 下测过了吗。

如果`_getSessionConfig`是为了兼容旧版本`mirai-api-http`而留下的东西，那么就可以close我的pr了。
但是新版并不存在`/config` API，故可能应当将`_getSessionConfig`标上`@deprecated`或完全删除此方法。
这是原代码：
```typescript
var {
  data: { data: { msg: message, code, cacheSize, enableWebsocket } },
} = responseData;
```
则data的数据格式会如下方所示。
```json
{
  "data":{
    "message":"",
    "code":0,
    "cacheSize":0,
    "enableWebsocket":true
  }
}
```
在我的修正过后，json变成了以下格式：
```json
{
  "message":"",
  "code":0,
  "cacheSize":0,
  "enableWebsocket":true
}
```
而这和提到的`{data: any, code: number, msg: string}`虽然可能有部分偏差，但前者无疑是错误的。

2022-08-01 15:21 UTC, Drincann commented
@FurryR 主要是我不知道你测了没有，我抽时间测一下看看吧。

2022-08-02 10:42 UTC, closed without merging