Better type checking
Drincann/Mirai-js pull request #219
Opened 2022-08-02 12:46 UTC by Mantou1233

fix #213 
Added autocorrect on `<Bot>.on`
tweaked a bit

2022-08-02 13:28 UTC, Drincann requested changes
麻烦把 style 的改动去掉，如果要修改 style，可以单独开一个 pr 交流。

2022-08-02 13:34 UTC, Drincann requested changes

2022-08-02 13:34 UTC, Drincann commented on src/BaseType.d.ts
> +interface BaseType {
这个 `BaseType` 在命名上语义不明确。

2022-08-02 13:39 UTC, Mantou1233 commented
> 麻烦把 style 的改动去掉，如果要修改 style，可以单独开一个 pr 交流。

oops

2022-08-03 06:59 UTC, Mantou1233 commented on src/BaseType.d.ts
> +interface BaseType {
那要命名成什么

2022-08-03 12:16 UTC, Drincann commented on src/BaseType.d.ts
> +interface BaseType {
`EventBaseType` 之类的。。

2022-08-05 05:43 UTC, Mantou1233 commented
done

2022-08-05 06:00 UTC, Drincann requested changes

2022-08-05 06:00 UTC, Drincann commented on src/BaseType.d.ts
> +	MessageChainGetable,
还是 style 的问题，麻烦把功能无关的改动去掉。

2022-08-05 06:11 UTC, Mantou1233 commented
ok

2022-08-06 06:33 UTC, Drincann commented
感谢帮忙，我抽空合一下测测看

2022-08-06 06:44 UTC, Drincann approved these changes

2022-08-06 06:46 UTC, merged

2022-08-06 06:53 UTC, Drincann commented
麻烦下次可以先过一下 git hook，多谢。

2022-08-06 07:09 UTC, Drincann commented
published to mirai-js@2.8.0-0(preminor)